from random import randint

def make_status_message():
    Quote = []
    Quote.append("* One Ruler to rule them all, One Ruler to find them, One Ruler to bring them all, and in a file bind them (Ruler). *")

    Quote.append("* No matter what you look at, if you look at it closely enough, you are involved in the entire universe (Michael Faraday). *")
    Quote.append("* Nothing is too wonderful to be true if it be consistent with the laws of nature (Michael Faraday). *")
    Quote.append("* There's nothing quite as frightening as someone who knows they are right (Michael Faraday). *")
    Quote.append("* A man who is certain he is right is almost sure to be wrong (Michael Faraday). *")
    Quote.append("* But still try for who knows what is possible! (Michael Faraday). *")
    Quote.append("* I could trust a fact and always cross-question an assertion (Michael Faraday). *")

    Quote.append("* As long as our brain is a mystery, the universe, the reflection of the structure of the brain will also be a mystery (Ramón y Cajal). *")
    Quote.append("* Every man if he so desires becomes sculptor of his own brain (Ramón y Cajal). *")
    Quote.append("* In summary, all great work is the fruit of patience and perseverance, combined with tenacious concentration on a subject over a period of months or years (Ramón y Cajal). *")
    Quote.append("* The worst part is not in making a mistake but in trying to justify it, instead of using it as a heaven-sent warning of our mindlessness or our ignorance (Ramón y Cajal). *")
    Quote.append("* Unfortunately, nature seems unaware of our intellectual need for convenience and unity, and very often takes delight in complication and diversity (Ramón y Cajal). *")
    Quote.append("* There are no small problems. Problems that appear small are large problems that are not understood (Ramón y Cajal). *")
    Quote.append("* It is idle to dispute with old men. Their opinions, like their cranial sutures, are ossified (Ramón y Cajal). *")
    Quote.append("* That which enters the mind through reason can be corrected. That which is admitted through faith, hardly ever (Ramón y Cajal). *")
    Quote.append("* Nothing inspires more reverence and awe in me than an old man who knows how to change his mind (Ramón y Cajal). *")

    Quote.append("* Insanity: doing the same thing over and over again and expecting different results (Einstein). *")
    Quote.append("* Imagination is more important than knowledge (Einstein). *")
    Quote.append("* Imagination is everything. It is the preview of life's coming attractions (Einstein). *")
    Quote.append("* If you can't explain it simply, you don't understand it well enough (Einstein). *")
    Quote.append("* Life is like riding a bicycle. To keep your balance you must keep moving (Einstein). *")
    Quote.append("* God does not play dice with the universe (Einstein). *")
    Quote.append("* The important thing is not to stop questioning. Curiosity has its own reason for existing (Einstein). *")
    Quote.append("* In the middle of difficulty lies opportunity (Einstein). *")
    Quote.append("* No problem can be solved from the same level of consciousness that created it (Einstein). *")
    Quote.append("* Try not to become a man of success, but rather try to become a man of value (Einstein). *")

    Quote.append("* What I cannot create, I do not understand (Feynmann). *")
    Quote.append("* The first principle is that you must not fool yourself and you are the easiest person to fool (Feynmann). *")
    Quote.append("* For a successful technology, reality must take precedence over public relations, for Nature cannot be fooled (Feynmann). *")
    Quote.append("* I was born not knowing and have had only a little time to change that here and there (Feynmann). *")

    Quote.append("* Nothing in life is to be feared, it is only to be understood. Now is the time to understand more, so that we may fear less (M. Curie). *")
    Quote.append("* Life is not easy for any of us. But what of that? We must have perseverance and above all confidence in ourselves (M. Curie). *")
    Quote.append("* Be less curious about people and more curious about ideas (M. Curie). *")
    Quote.append("* First principle: never to let one's self be beaten down by persons or by events (M. Curie). *")
    Quote.append("* You cannot hope to build a better world without improving the individuals (M. Curie). *")
    Quote.append("* I never see what has been done; I only see what remains to be done (M. Curie). *")
    Quote.append("* Now is the time to understand more, so we fear less (M. Curie). *")
    Quote.append("* You can only analyze the data you have. Be strategic about what to gather and how to store it (M. Curie). *")
    Quote.append("* I am among those who think that science has great beauty (M. Curie). *")
    Quote.append("* If it takes a hundred years, it will be a pity, but I will not cease to work for it as long as I live (M. Curie). *")
    Quote.append("* It was like a new world opened to me, the world of science, which I was at last permitted to know in all liberty (M. Curie). *")
    Quote.append("* I was taught the method for advancement is not quick or simple (M. Curie). *")
    Quote.append("* I have frequently been questioned, especially by women, of how I could reconcile family life with a scientific career. Well, it has not been easy (M. Curie). *")
    Quote.append("* After all, science is essentially international, and it is only through lack of the historical sense that national qualities have been attributed to it (M. Curie). *")
    Quote.append("* There are sadistic scientists who hurry to hunt down errors instead of establishing the truth (M. Curie). *")
    Quote.append("* We must not forget that when radium was discovered no one knew that it would prove useful in hospitals (M. Curie). *")
    Quote.append("* Life is not easy for any for us (M. Curie). *")
    Quote.append("* Scientist believe in things, not in person (M. Curie). *")

    Quote.append("* It is important to make a dream of life and a dream reality (P. Curie). *")

    Quote.append("* All of physics is either impossible or trivial. It is impossible until you understand it, and then it becomes trivial (Rutherford). *")
    Quote.append("* Never say, 'I tried it once and it did not work' (Rutherford). *")

    Quote.append("* Science and everyday life cannot and should not be separated (Rosalind Franklin). *")
    Quote.append("* Science, for me, gives a partial explanation for life. In so far as it goes, it is based on fact, experience and experiment (Rosalind Franklin). *")

    Quote.append("* I have also testified repeatedly and published some articles in favor of Small Science (Philip W. Anderson). *")
    Quote.append("* My objective was never to make money. I wanted to contribute to human knowledge and betterment (John B. Goodenough). *")
    Quote.append("* There are no roses without spins (Eugenio Coronado). *")
    Quote.append("* Pick a flower on Earth and you move the farthest star (Dirac). *")
    Quote.append("* Your theory is crazy, but it's not crazy enough to be true (Bohr). *")
    Quote.append("* Science is organized knowledge. Wisdom is organized life (Kant). *")
    Quote.append("* Science is nothing but perception (Plato). *")
    Quote.append("* Falsity in intellectual action is intellectual immorality (Chamberlin). *")
    Quote.append("* The saddest aspect of life right now is that gathers knowledge faster than society gathers wisdom (Asimov). *")
    Quote.append("* A man who dares to waste one hour of time has not discovered the value of life (Darwin). *")
    Quote.append("* The good thing about science is that it's true whether or not you believe in it (Tyson). *")
    Quote.append("* You cannot teach a man anything; you can only help him discover it in himself (Galileo). *")
    Quote.append("* Shall I refuse my dinner because I do not fully understand the process of digestion? (Oliver Heaviside). *")
    Quote.append("* If I have seen further it is by standing on the shoulders of Giants (Isaac Newton). *")

    Quote.append("* Science is a way of thinking much more than it is a body of knowledge (Carl Sagan). *")
    Quote.append("* The art and science of asking questions is the source of all knowledge (Thomas Berger). *")
    Quote.append("* Science without religion is lame, religion without science is blind (Albert Einstein). *")
    Quote.append("* Science is organized knowledge. Wisdom is organized life (Immanuel Kant). *")
    Quote.append("* The saddest aspect of life right now is that science gathers knowledge faster than society gathers wisdom (Isaac Asimov). *")
    Quote.append("* Scientists have become the bearers of the torch of discovery in our quest for knowledge (Stephen Hawking). *")
    Quote.append("* Success is a science; if you have the conditions, you get the result (Oscar Wilde). *")
    Quote.append("* It is strange that only extraordinary men make the discoveries, which later appear so easy and simple (Georg C. Lichtenberg). *")
    Quote.append("* Progress is made by trial and failure; the failures are generally a hundred times more numerous than the successes; yet they are usually left unchronicled (W. Ramsay). *")
    Quote.append("* Research is what I’m doing when I don’t know what I’m doing (Wernher von Braun). *")
    Quote.append("* In questions of science, the authority of a thousand is not worth the humble reasoning of a single individual (Galileo Galilei). *")
    Quote.append("* “Everything is theoretically impossible, until it is done (Robert A. Heinlein). *")
    Quote.append("* The good thing about science is that it’s true whether or not you believe in it (Neil deGrasse Tyson). *")
    Quote.append("* Nothing in life is to be feared, it is only to be understood. Now is the time to understand more, so that we may fear less (Marie Curie). *")
    Quote.append("* Shall I refuse my dinner because I do not fully understand the process of digestion? (Oliver Heaviside). *")
    Quote.append("* Science is the acceptance of what works and the rejection of what does not. That needs more courage than we might think (J. Bronowski). *")
    Quote.append("* I learned very early the difference between knowing the name of something and knowing something (Richard P. Feynman). *")
    Quote.append("* The beauty of a living thing is not the atoms that go into it, but the way those atoms are put together (Carl Sagan). *")
    Quote.append("* The whole of science is nothing more than a refinement of everyday thinking (Albert Einstein). *")
    Quote.append("* Science is the knowledge of consequences, and dependence of one fact upon another (Thomas Hobbes). *")
    Quote.append("* Every great advance in science has issued from a new audacity of imagination (John Dewey). *")
    Quote.append("* Bad times have a scientific value. These are occasions a good learner would not miss (Ralph Waldo Emerson). *")
    Quote.append("* You cannot teach a man anything; you can only help him discover it in himself (Galileo). *")
    Quote.append("* I never teach my pupils. I only attempt to provide the conditions in which they can learn (Albert Einstein). *")
    Quote.append("* An experiment is a question which science poses to Nature, and a measurement is the recording of Nature’s answer (Max Plank). *")
    Quote.append("* Equipped with his five senses, man explores the universe around him and calls the adventure Science (E. P. Hubble). *")
    Quote.append("* The scientist is not a person who gives the right answers, he’s one who asks the right questions (Claude Levi-Strauss). *")
    Quote.append("* Science is the great antidote to the poison of enthusiasm and superstition (Adam Smith). *")
    Quote.append("* Gravitation is not responsible for people falling in love (Albert Einstein). *")
    Quote.append("* To invent, you need a good imagination and a pile of junk (Thomas A. Edison). *")
    Quote.append("* In scientific work, those who refuse to go beyond fact rarely get as far as fact (Thomas Huxley). *")
    Quote.append("* What we know is a drop, what we don’t know is an ocean (Isaac Newton). *")
    Quote.append("* What I love about science is that as you learn, you don’t really get answers. You just get better questions (John Green). *")
    Quote.append("* All sciences are vain and full of errors that are not born of Experience, the mother of all Knowledge (Leonardo da Vinci). *")
    Quote.append("* Science is magic that works (Kurt Vonnegut). *")
    Quote.append("* Never memorize something that you can look up (Albert Einstein). *")
    Quote.append("* An expert is a person who has made all the mistakes that can be made in a very narrow field (Niels Bohr). *")
    Quote.append("* Men love to wonder, and that is the seed of science (Ralph Waldo Emerson). *")
    Quote.append("* Science and everyday life cannot and should not be separated (Rosalind Franklin). *")
    Quote.append("* What you learn from a life in science is the vastness of our ignorance (David Eagleman). *")
    Quote.append("* Science is not only a disciple of reason but also one of romance and passion (Stephen Hawking). *")
    Quote.append("* Until man duplicates a blade of grass, nature can laugh at his so-called scientific knowledge (Thomas Edison). *")
    Quote.append("* Science knows no country, because knowledge belongs to humanity, and is the torch which illuminates the world (Louis Pasteur). *")
    Quote.append("* A scientist in his laboratory is not a mere technician: he is also a child confronting natural phenomena that impress him as though they were fairy tales (M. Curie). *")
    Quote.append("* The most important thing is to never stop questioning (Albert Einstein). *")
    Quote.append("* Somewhere, something incredible is waiting to be known (Carl Sagan). *")
    Quote.append("* Falsity in intellectual action is intellectual immorality (Thomas Crowder Chamberlain). *")
    Quote.append("* Real science can be far stranger than science fiction and much more satisfying (Stephen Hawking). *")
    Quote.append("* Science is simply the word to describe a method of organizing our curiosity ( Tim Minchin). *")
    Quote.append("* Wonder is the heaviest element on the periodic table. Even a tiny fleck of it stops time (Diane Ackerman). *")


    status_message = Quote[randint(0,len(Quote)-1)]
    return status_message
